version: '3.9'

services:
  tgbot_app:
    build:
      context: ./tgbot_app
      dockerfile: Dockerfile
    restart: always
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
    depends_on:
      - redis
    ports:
     - "222:222"

  redis:
    image: redis
    container_name: redis
    restart: always
    command: redis-server --requirepass ${R_PASSWORD}
    environment:
      - R_PASSWORD=${R_PASSWORD}
    ports:
      - "6379:6379"

  db:
    image: postgres
    container_name: db
    shm_size: 128mb
    restart: always
    volumes:
      - some_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

  fastapi_app:
    build: ./fastapi_app
    container_name: fastapi_app
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"

  nginx:
    image: nginx
    container_name: my-nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cert.pem:/etc/cert.pem
      - ./nginx/key.pem:/etc/key.pem
    ports:
      - "80:80"
      - "443:443"

  certbot:
    build:
      context: ./certbot
      dockerfile: Dockerfile
      args:
        DOMAIN_EMAIL: ${DOMAIN_EMAIL}
        DOMAIN_URL: ${DOMAIN_URL}
    depends_on:
      - nginx
    volumes:
      - ./nginx/:/etc/nginx/
    ports:
      - "6000:80"

volumes:
  some_volume: