version: '3.9'

services:
  tgbot_app:
    build:
      context: ./tgbot_app
      dockerfile: Dockerfile
    restart: always
    environment:
      - REDIS_HOST=redis
      - DB_HOST=postgres
    depends_on:
      - redis
    ports:
     - "222:222"

  redis:
    image: redis
    restart: always
    command: redis-server --requirepass ${R_PASSWORD}
    environment:
      - R_PASSWORD=${R_PASSWORD}
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    shm_size: 128mb
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

  fastapi_app:
    build: ./fastapi_app
    restart: always
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  nginx:
    build: nginx
    container_name: my-nginx
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./reverse_proxy/cert.pem:/etc/cert.pem
      - ./reverse_proxy/key.pem:/etc/key.pem
    ports:
      - "80:80"
      - "443:443"

  certbot:
    build:
      context: ./certbot
      dockerfile: Dockerfile
    volumes:
      - ./reverse_proxy/:/etc/nginx/
    ports:
      - "6000:80"
    args:
        DOMAIN_EMAIL: ${DOMAIN_EMAIL}
        DOMAIN_URL: ${DOMAIN_URL}
